[package]
name = "refscape-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "refscape"
path = "src/main.rs"

[dependencies]
refscape-application.workspace = true
refscape-language.workspace = true
refscape-model.workspace = true
refscape-storage.workspace = true
refscape-ui.workspace = true

[lints]
workspace = true
