use std::{collections::BTreeMap, fs, path::Path};

use cargo_metadata::{Dependency, DependencyKind, Metadata, MetadataCommand, Package};

const MODEL: &str = "refscape-model";
const ANALYSIS: &str = "refscape-analysis";
const SUPPORT: &str = "refscape-language-support";
const CANVAS: &str = "refscape-canvas";
const APPLICATION: &str = "refscape-application";
const LSP: &str = "refscape-lsp";
const RUST: &str = "refscape-language-rust";
const CPP: &str = "refscape-language-cpp";
const TYPESCRIPT: &str = "refscape-language-typescript";
const PYTHON: &str = "refscape-language-python";
const LANGUAGE: &str = "refscape-language";
const STORAGE: &str = "refscape-storage";
const UI: &str = "refscape-ui";
const APP: &str = "refscape-app";

// A new member must be deliberately registered here; no default allow rule.
const POLICY: &[(&str, &[&str])] = &[
    (MODEL, &[]),
    (ANALYSIS, &[MODEL]),
    (CANVAS, &[MODEL]),
    (APPLICATION, &[MODEL, ANALYSIS, CANVAS]),
    (LSP, &[MODEL, ANALYSIS]),
    (SUPPORT, &[MODEL, ANALYSIS, LSP]),
    (RUST, &[MODEL, ANALYSIS, LSP, SUPPORT]),
    (CPP, &[MODEL, ANALYSIS, LSP, SUPPORT]),
    (TYPESCRIPT, &[MODEL, ANALYSIS, LSP, SUPPORT]),
    (PYTHON, &[MODEL, ANALYSIS, LSP, SUPPORT]),
    (
        LANGUAGE,
        &[MODEL, ANALYSIS, SUPPORT, RUST, CPP, TYPESCRIPT, PYTHON],
    ),
    (STORAGE, &[MODEL, APPLICATION]),
    (UI, &[MODEL, APPLICATION]),
    (APP, &[MODEL, ANALYSIS, APPLICATION, LANGUAGE, STORAGE, UI]),
];

struct Edge {
    to: String,
    description: String,
}

type Graph = BTreeMap<String, Vec<Edge>>;

/// Validate declared internal dependencies, including disabled features and targets.
/// Any metadata, manifest, or identity error fails the check closed.
pub fn check_architecture(root: &Path) -> Result<String, String> {
    let graph = inspect_architecture(root)?;
    let edges: usize = graph.values().map(Vec::len).sum();
    Ok(format!(
        "architecture passed: {} product crates, {edges} declared internal dependencies; xtask isolated",
        graph.len()
    ))
}

/// Render validated internal and direct external dependencies reproducibly.
pub fn dependency_graph(root: &Path) -> Result<String, String> {
    let graph = inspect_architecture(root)?;
    let mut document = String::from(
        "# Dependency graph\n\n\
         <!-- Generated by cargo xtask graph. Do not edit manually. -->\n\n\
         矢印は依存する crate から依存先へ向かう。\n\n\
         ## Internal dependencies\n\n\
         製品の内部依存宣言を表示し、dev・build・optional・target 固有の依存も含む。\n\
         `xtask` は独立した workspace で、製品への依存を持たない。\n\n\
         ```mermaid\nflowchart TD\n    subgraph product[\"Product workspace\"]\n",
    );
    for name in graph.keys() {
        document.push_str(&format!("        {}[\"{name}\"]\n", node_id(name)));
    }
    for (from, edges) in &graph {
        for edge in edges {
            document.push_str(&format!(
                "        {} -->|\"{}\"| {}\n",
                node_id(from),
                mermaid_label(&edge.description),
                node_id(&edge.to)
            ));
        }
    }
    document.push_str("    end\n    subgraph tooling[\"Tooling workspace\"]\n        xtask[\"xtask\"]\n    end\n```\n");
    append_external_graph(root, &graph, &mut document)?;
    Ok(document)
}

fn append_external_graph(
    root: &Path,
    internal: &Graph,
    document: &mut String,
) -> Result<(), String> {
    let mut external: Graph = internal.keys().map(|name| (name.clone(), vec![])).collect();
    external.insert("xtask".into(), vec![]);
    for manifest in [root.join("Cargo.toml"), root.join("xtask/Cargo.toml")] {
        let metadata = metadata(&manifest)?;
        for package in &metadata.packages {
            if !metadata.workspace_members.contains(&package.id) {
                continue;
            }
            let declarations = read_manifest(package.manifest_path.as_std_path())?;
            let edges = external
                .get_mut(package.name.as_str())
                .ok_or_else(|| format!("missing external graph node: {}", package.name))?;
            for dependency in &package.dependencies {
                if internal.contains_key(&dependency.name) {
                    continue;
                }
                let alias = dependency.rename.as_deref().unwrap_or(&dependency.name);
                let mut description = describe(dependency);
                if alias != dependency.name {
                    description.push_str(&format!(", alias={alias}"));
                }
                if declaration(&declarations, dependency, alias)?
                    .get("workspace")
                    .and_then(toml::Value::as_bool)
                    == Some(true)
                {
                    description.push_str(", workspace");
                }
                edges.push(Edge {
                    to: dependency.name.clone(),
                    description,
                });
            }
            edges.sort_by(|left, right| {
                (&left.to, &left.description).cmp(&(&right.to, &right.description))
            });
        }
    }
    // Use deterministic numeric IDs so distinct names such as foo-bar and foo_bar
    // never collapse into one Mermaid node after identifier normalization.
    let mut destinations = BTreeMap::new();
    for edges in external.values() {
        for edge in edges {
            destinations.insert(edge.to.as_str(), 0);
        }
    }
    for (index, id) in destinations.values_mut().enumerate() {
        *id = index;
    }
    document.push_str(
        "\n## Direct external dependencies\n\n\
         各 crate の Cargo.toml に宣言された直接の外部依存を表示する。\n\
         推移依存は含めず、同じ package 名への依存は一つのノードにまとめる。\n\
         dev・build・optional・target 固有の宣言も含み、別名は `alias`、workspace 継承は `workspace` で示す。\n\
         `xtask` の外部依存は製品 workspace と分けて表示する。\n\n\
         ```mermaid\nflowchart LR\n    subgraph product[\"Product workspace\"]\n",
    );
    for name in internal.keys() {
        document.push_str(&format!("        {}[\"{name}\"]\n", node_id(name)));
    }
    document.push_str("    end\n    subgraph tooling[\"Tooling workspace\"]\n        xtask[\"xtask\"]\n    end\n    subgraph external[\"Direct external crates\"]\n");
    for (name, id) in &destinations {
        document.push_str(&format!(
            "        external_{id}[\"{}\"]\n",
            mermaid_label(name)
        ));
    }
    document.push_str("    end\n");
    for (from, edges) in &external {
        for edge in edges {
            document.push_str(&format!(
                "    {} -->|\"{}\"| external_{}\n",
                node_id(from),
                mermaid_label(&edge.description),
                destinations[edge.to.as_str()]
            ));
        }
    }
    document.push_str("```\n");
    Ok(())
}

/// Write only after the entire architecture has passed validation.
pub fn write_dependency_graph(root: &Path) -> Result<String, String> {
    let document = dependency_graph(root)?;
    let path = root.join("docs/dependency-graph.md");
    fs::create_dir_all(root.join("docs"))
        .map_err(|error| format!("cannot create docs directory: {error}"))?;
    fs::write(&path, document)
        .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    Ok(format!("generated {}", path.display()))
}

fn node_id(name: &str) -> String {
    name.replace('-', "_")
}

fn mermaid_label(label: &str) -> String {
    let mut escaped = String::new();
    for character in label.chars() {
        match character {
            '"' => escaped.push_str("#34;"),
            '#' => escaped.push_str("#35;"),
            '&' => escaped.push_str("#38;"),
            '<' => escaped.push_str("#60;"),
            '>' => escaped.push_str("#62;"),
            '|' => escaped.push_str("#124;"),
            '\n' | '\r' => escaped.push(' '),
            _ => escaped.push(character),
        }
    }
    escaped
}

fn inspect_architecture(root: &Path) -> Result<Graph, String> {
    let root = root
        .canonicalize()
        .map_err(|error| format!("cannot resolve repository root: {error}"))?;
    let metadata = metadata(&root.join("Cargo.toml"))?;
    let mut members = BTreeMap::new();
    for id in &metadata.workspace_members {
        let package = metadata
            .packages
            .iter()
            .find(|package| &package.id == id)
            .ok_or_else(|| format!("metadata is missing workspace member {id}"))?;
        let name = package.name.as_str();
        if !POLICY.iter().any(|(known, _)| *known == name) {
            return Err(format!("unregistered workspace member: {name}"));
        }
        let expected = root.join("crates").join(name).join("Cargo.toml");
        if canonical_manifest(package)? != canonical(&expected)? {
            return Err(format!("{name} must be located at {}", expected.display()));
        }
        if members.insert(name.to_owned(), package).is_some() {
            return Err(format!("duplicate workspace package name: {name}"));
        }
    }
    for (name, _) in POLICY {
        if !members.contains_key(*name) {
            return Err(format!("required workspace member is missing: {name}"));
        }
    }

    let manifest = read_manifest(&root.join("Cargo.toml"))?;
    let shared = manifest
        .get("workspace")
        .and_then(|value| value.get("dependencies"))
        .and_then(toml::Value::as_table)
        .ok_or("root manifest must define [workspace.dependencies]")?;
    for (alias, declaration) in shared {
        let package = declaration
            .get("package")
            .and_then(toml::Value::as_str)
            .unwrap_or(alias);
        if package == "gpui" || package.starts_with("gpui_") {
            return Err("GPUI dependencies must be declared directly in refscape-ui, not workspace.dependencies".into());
        }
    }
    for name in members.keys() {
        let declaration = shared
            .get(name)
            .ok_or_else(|| format!("missing workspace.dependencies.{name}"))?;
        check_shared_dependency(&root, name, declaration, members[name])?;
    }

    let mut graph: Graph = members.keys().map(|name| (name.clone(), vec![])).collect();
    let mut violations = vec![];
    let mut gpui_revision = None;
    for (name, package) in &members {
        let manifest = read_manifest(package.manifest_path.as_std_path())?;
        for dependency in &package.dependencies {
            let destination = internal_destination(dependency, &members)?;
            let Some(destination) = destination else {
                check_external_boundary(name, dependency, &mut violations);
                if name == UI && (dependency.name == "gpui" || dependency.name.starts_with("gpui_"))
                {
                    let alias = dependency.rename.as_deref().unwrap_or(&dependency.name);
                    let declaration = declaration(&manifest, dependency, alias)?;
                    check_gpui_source(declaration)?;
                    let revision = declaration
                        .get("rev")
                        .and_then(toml::Value::as_str)
                        .ok_or("missing GPUI rev")?;
                    if let Some(previous) = gpui_revision.replace(revision.to_owned())
                        && previous != revision
                    {
                        violations
                            .push("all GPUI dependencies must use the same pinned revision".into());
                    }
                }
                continue;
            };
            let alias = dependency.rename.as_deref().unwrap_or(&dependency.name);
            let declaration = declaration(&manifest, dependency, alias)?;
            if declaration.get("workspace").and_then(toml::Value::as_bool) != Some(true) {
                violations.push(format!(
                    "{name}: internal dependency {alias} must use workspace = true"
                ));
            }
            let shared_declaration = shared
                .get(alias)
                .ok_or_else(|| format!("missing workspace.dependencies.{alias}"))?;
            check_shared_dependency(&root, alias, shared_declaration, members[destination])?;
            let description = describe(dependency);
            graph.get_mut(name).ok_or("missing graph node")?.push(Edge {
                to: destination.to_owned(),
                description: description.clone(),
            });
            let allowed = POLICY
                .iter()
                .find(|(known, _)| known == name)
                .ok_or("missing dependency policy")?
                .1;
            if !allowed.contains(&destination) {
                violations.push(format!(
                    "forbidden dependency: {name} --{description}--> {destination}"
                ));
            }
        }
    }
    for edges in graph.values_mut() {
        edges.sort_by(|left, right| {
            (&left.to, &left.description).cmp(&(&right.to, &right.description))
        });
    }
    if let Some(cycle) = find_cycle(&graph) {
        violations.insert(0, format!("dependency cycle:\n{cycle}"));
    }
    check_xtask(&root)?;
    if !violations.is_empty() {
        return Err(violations.join("\n"));
    }
    Ok(graph)
}

fn check_gpui_source(gpui: &toml::Value) -> Result<(), String> {
    if gpui.get("git").and_then(toml::Value::as_str)
        != Some("https://github.com/zed-industries/zed")
    {
        return Err("GPUI must come from https://github.com/zed-industries/zed".into());
    }
    let revision = gpui
        .get("rev")
        .and_then(toml::Value::as_str)
        .ok_or("GPUI must be pinned with a full commit rev")?;
    if revision.len() != 40 || !revision.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err("GPUI rev must be a full 40-character commit hash".into());
    }
    if ["branch", "tag", "path", "registry", "version", "workspace"]
        .iter()
        .any(|key| gpui.get(key).is_some())
    {
        return Err("GPUI must use only its pinned Zed git source".into());
    }
    Ok(())
}

fn metadata(manifest: &Path) -> Result<Metadata, String> {
    MetadataCommand::new()
        .manifest_path(manifest)
        .no_deps()
        .exec()
        .map_err(|error| format!("cannot inspect {}: {error}", manifest.display()))
}

fn read_manifest(path: &Path) -> Result<toml::Table, String> {
    fs::read_to_string(path)
        .map_err(|error| format!("cannot read {}: {error}", path.display()))?
        .parse()
        .map_err(|error| format!("invalid manifest {}: {error}", path.display()))
}

fn canonical(path: &Path) -> Result<std::path::PathBuf, String> {
    path.canonicalize()
        .map_err(|error| format!("cannot resolve {}: {error}", path.display()))
}

fn canonical_manifest(package: &Package) -> Result<std::path::PathBuf, String> {
    canonical(package.manifest_path.as_std_path())
}

fn check_shared_dependency(
    root: &Path,
    alias: &str,
    declaration: &toml::Value,
    destination: &Package,
) -> Result<(), String> {
    let path = declaration
        .get("path")
        .and_then(toml::Value::as_str)
        .ok_or_else(|| {
            format!("workspace.dependencies.{alias} must identify an internal crate by path")
        })?;
    if canonical(&root.join(path).join("Cargo.toml"))? != canonical_manifest(destination)? {
        return Err(format!(
            "workspace.dependencies.{alias} points to the wrong package"
        ));
    }
    if declaration.get("git").is_some() || declaration.get("registry").is_some() {
        return Err(format!(
            "workspace.dependencies.{alias} must not use git or registry"
        ));
    }
    let name = declaration
        .get("package")
        .and_then(toml::Value::as_str)
        .unwrap_or(alias);
    if name != destination.name.as_str() {
        return Err(format!(
            "workspace.dependencies.{alias} has the wrong package name"
        ));
    }
    Ok(())
}

fn internal_destination<'a>(
    dependency: &Dependency,
    members: &'a BTreeMap<String, &Package>,
) -> Result<Option<&'a str>, String> {
    if let Some(path) = &dependency.path {
        let manifest = canonical(path.join("Cargo.toml").as_std_path())?;
        for (name, package) in members {
            if canonical_manifest(package)? == manifest {
                if dependency.name != *name {
                    return Err(format!(
                        "dependency package identity mismatch: {}",
                        dependency.name
                    ));
                }
                return Ok(Some(name));
            }
        }
        return Err(format!(
            "unregistered local path dependency: {} at {path}",
            dependency.name
        ));
    }
    if members.contains_key(&dependency.name) || dependency.name == "xtask" {
        return Err(format!(
            "internal dependency {} must use a workspace path, not a registry or git source",
            dependency.name
        ));
    }
    Ok(None)
}

fn declaration<'a>(
    manifest: &'a toml::Table,
    dependency: &Dependency,
    alias: &str,
) -> Result<&'a toml::Value, String> {
    let section = match dependency.kind {
        DependencyKind::Normal => "dependencies",
        DependencyKind::Development => "dev-dependencies",
        DependencyKind::Build => "build-dependencies",
        _ => return Err("unsupported dependency kind".into()),
    };
    let value = if let Some(target) = &dependency.target {
        manifest
            .get("target")
            .and_then(toml::Value::as_table)
            .and_then(|targets| {
                targets.iter().find_map(|(expression, value)| {
                    let parsed = expression
                        .parse::<cargo_metadata::cargo_platform::Platform>()
                        .ok()?;
                    (parsed == *target).then_some(value)
                })
            })
            .and_then(|value| value.get(section))
    } else {
        manifest.get(section)
    };
    value
        .and_then(|value| value.get(alias))
        .ok_or_else(|| format!("cannot locate declaration of {alias} in {section}"))
}

fn describe(dependency: &Dependency) -> String {
    let mut result = match dependency.kind {
        DependencyKind::Normal => "normal",
        DependencyKind::Development => "dev",
        DependencyKind::Build => "build",
        _ => "unknown",
    }
    .to_owned();
    if dependency.optional {
        result.push_str(", optional");
    }
    if let Some(target) = &dependency.target {
        result.push_str(&format!(", target={target}"));
    }
    result
}

fn check_external_boundary(name: &str, dependency: &Dependency, violations: &mut Vec<String>) {
    if (dependency.name == "gpui" || dependency.name.starts_with("gpui_")) && name != UI {
        violations.push(format!(
            "{name}: GPUI dependencies are only allowed in {UI}"
        ));
    }
    if dependency.name == "lsp-types" && name != LSP {
        violations.push(format!("{name}: lsp-types is only allowed in {LSP}"));
    }
}

fn check_xtask(root: &Path) -> Result<(), String> {
    let manifest = root.join("xtask/Cargo.toml");
    let metadata = metadata(&manifest)?;
    if metadata.workspace_members.len() != 1
        || canonical(metadata.workspace_root.as_std_path())? != canonical(&root.join("xtask"))?
    {
        return Err("xtask must be a standalone, single-package workspace".into());
    }
    let package = metadata
        .packages
        .iter()
        .find(|package| package.id == metadata.workspace_members[0])
        .ok_or("xtask metadata is missing its workspace member")?;
    if package.name.as_str() != "xtask" || canonical_manifest(package)? != canonical(&manifest)? {
        return Err("xtask package identity is invalid".into());
    }
    for dependency in &package.dependencies {
        if dependency.path.is_some()
            || dependency.name == "xtask"
            || POLICY.iter().any(|(name, _)| *name == dependency.name)
        {
            return Err(format!(
                "xtask must not depend on product or local crates: {}",
                dependency.name
            ));
        }
    }
    Ok(())
}

fn find_cycle(graph: &Graph) -> Option<String> {
    let mut states: BTreeMap<&str, u8> = graph.keys().map(|name| (name.as_str(), 0)).collect();
    let mut nodes = vec![];
    let mut path = vec![];
    for name in graph.keys() {
        if states[name.as_str()] == 0
            && let Some(cycle) = visit(name, graph, &mut states, &mut nodes, &mut path)
        {
            return Some(cycle);
        }
    }
    None
}

fn visit<'a>(
    name: &'a str,
    graph: &'a Graph,
    states: &mut BTreeMap<&'a str, u8>,
    nodes: &mut Vec<&'a str>,
    path: &mut Vec<&'a Edge>,
) -> Option<String> {
    states.insert(name, 1);
    nodes.push(name);
    for edge in &graph[name] {
        match states[edge.to.as_str()] {
            0 => {
                path.push(edge);
                if let Some(cycle) = visit(&edge.to, graph, states, nodes, path) {
                    return Some(cycle);
                }
                path.pop();
            }
            1 => {
                let start = nodes.iter().position(|node| *node == edge.to)?;
                let mut cycle = format!("  {}", nodes[start]);
                for step in path
                    .iter()
                    .skip(start)
                    .copied()
                    .chain(std::iter::once(edge))
                {
                    cycle.push_str(&format!("\n    --{}--> {}", step.description, step.to));
                }
                return Some(cycle);
            }
            _ => {}
        }
    }
    nodes.pop();
    states.insert(name, 2);
    None
}
